package org.ufa.security.model;

import org.springframework.security.core.GrantedAuthority;
import org.ufa.core.model.BaseObject;

public class UfaBaseRole extends BaseObject implements GrantedAuthority{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ROLE_ID
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ROLE_NAME
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.DESCRIPTION
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ROLE_ID
     *
     * @return the value of T_ROLE.ROLE_ID
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ROLE_ID
     *
     * @param roleId the value for T_ROLE.ROLE_ID
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ROLE_NAME
     *
     * @return the value of T_ROLE.ROLE_NAME
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ROLE_NAME
     *
     * @param roleName the value for T_ROLE.ROLE_NAME
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.DESCRIPTION
     *
     * @return the value of T_ROLE.DESCRIPTION
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.DESCRIPTION
     *
     * @param description the value for T_ROLE.DESCRIPTION
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

	@Override
	public String getAuthority() {
		return this.getRoleName();
	}
}