package org.ufa.security.model;

import org.ufa.core.model.BaseObject;

public class UfaBaseResource extends BaseObject{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RESOURCE.RESOURCE_ID
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    private Long resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RESOURCE.RESOURCE_NAME
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RESOURCE.URL
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_RESOURCE.METHOD
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    private String method;

    private String appId;
    
    public String getAppId() {
		return appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RESOURCE.RESOURCE_ID
     *
     * @return the value of T_RESOURCE.RESOURCE_ID
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RESOURCE.RESOURCE_ID
     *
     * @param resourceId the value for T_RESOURCE.RESOURCE_ID
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RESOURCE.RESOURCE_NAME
     *
     * @return the value of T_RESOURCE.RESOURCE_NAME
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RESOURCE.RESOURCE_NAME
     *
     * @param resourceName the value for T_RESOURCE.RESOURCE_NAME
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RESOURCE.URL
     *
     * @return the value of T_RESOURCE.URL
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RESOURCE.URL
     *
     * @param url the value for T_RESOURCE.URL
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_RESOURCE.METHOD
     *
     * @return the value of T_RESOURCE.METHOD
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_RESOURCE.METHOD
     *
     * @param method the value for T_RESOURCE.METHOD
     *
     * @mbggenerated Fri Jun 08 12:39:14 CST 2012
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }
}