seajs.config({
    alias:{
        'jquery':'jquery/1.9.1/jquery-debug.js',
        'accordion':'taurus/accordion/1.10.0/jquery.ui.accordion-debug.js',
        'art-dialog':'taurus/art-dialog/4.1.6/dialog-debug.js',
        'autocomplete':'taurus/autocomplete/1.1.0/autocomplete-debug.js',
        'base64':'taurus/base64/1.0.0/base64-debug.js',
        'bgiframe':'taurus/bgiframe/2.1.2/jquery.bgiframe-debug.js',
        'block':'taurus/block/2.57.0/block-debug.js',
        'button':'taurus/button/1.10.0/jquery.ui.button-debug.js',
        'cookie':'taurus/cookie/1.0.0/jquery.cookie-debug.js',
        'datepicker':'taurus/datepicker/1.10.0/datepicker-debug.js',
        'datatables':'taurus/datatables/1.9.4/jquery.datatables-debug.js',
        'dialog':'taurus/dialog/1.10.0/dialog-debug.js',
        'draggable':'taurus/draggable/1.10.0/jquery.ui.draggable-debug.js',
        'editor':'taurus/editor/4.1.5/kindeditor-debug.js',
        'excanvas':'taurus/excanvas/2.0/excanvas-debug.js',
        'globalize':'taurus/spinner/1.10.0/globalize-debug.js',
        'grid':'taurus/grid/1.0.0/grid-debug.js',
        'hotkeys':'taurus/hotkeys/1.0.0/hotkeys-debug.js',
        'jeditable' : 'taurus/datatables/1.9.4/jquery.jeditable-debug.js',
        'jqgrid':'taurus/jqgrid/4.4.4/jqgrid-debug.js',
        'json': 'json/1.0.2/json-debug.js',
        'listnav':'taurus/listnav/2.1.0/listnav-debug.js',
        'menu':'taurus/menu/1.10.0/jquery.ui.menu-debug.js',
        'moment':'taurus/moment/1.7.2/moment-debug.js',
        'mouse':'taurus/mouse/1.10.0/jquery.ui.mouse-debug.js',
        'password':'taurus/password/1.0.0/password-debug.js',
        'placeholder':'taurus/placeholder/1.0.0/placeholder-debug.js',
        'position':'taurus/position/1.10.0/jquery.ui.position-debug.js',
        'querystring':'taurus/querystring/1.0.0/querystring-debug.js',
        'resizable':'taurus/resizable/1.10.0/jquery.ui.resizable-debug.js',
        'slider':'taurus/slider/1.10.0/jquery.ui.slider-debug.js',
        'mousewheel':'taurus/spinner/1.10.0/jquery.mousewheel-debug.js',//spinner mousewheel依赖包
        'spinner':'taurus/spinner/1.10.0/jquery.ui.spinner-debug.js',
        'sortable':'taurus/sortable/1.10.0/jquery.ui.sortable-debug.js',
        'progressbar':'taurus/progressbar/1.10.0/jquery.ui.progressbar-debug.js',
        'tabs':'taurus/tabs/1.10.0/jquery.ui.tabs-debug.js',
        'timepicker':'taurus/timepicker/1.1.1/timepicker-debug.js',
        'tip':'taurus/tip/0.9.5/jquery.bt-debug.js',
        'tooltip':'taurus/tooltip/1.10.0/jquery.ui.tooltip-debug.js',
        'tree' : 'taurus/tree/3.5.02/tree.core-debug.js',
        'tree-excheck' : 'taurus/tree/3.5.02/tree.excheck-debug.js',
        'tree-exedit' : 'taurus/tree/3.5.02/tree.exedit-debug.js',
        'tree-exhide' : 'taurus/tree/3.5.02/tree.exhide-debug.js',
        'upload':'taurus/upload/3.2.0/jquery.uploadify-debug.js',
        'validation':'taurus/validation/1.11.0/validation-debug.js',
        'zoom':'taurus/zoom/1.0.2/zoom-debug.js',
        'combobox':'taurus/combobox/1.10.0/jquery.ui.combobox-debug.js',
        'pinyin':'taurus/pinyin/1.0.0/pinyin-debug.js',
        'handlebars':'taurus/handlebars/1.0.0/handlebars-debug.js',
        'combobox-css':'style/combobox.css',
        'art-dialog-css':'style/art-dialog/skins/default.css',
        'jquery-css' : 'style/jquery.css',
        'jquery-default-css' : 'style/jquery-default.css'
    },
    preload : [ 'jquery']
});
